services:
  openblow:
    image: mitrakov/openblow:1.0.0
    hostname: openblow.host
    environment:
      - IS_MASTER=true
      - MASTER_HOST=openblow.host
      - WORKER_HOSTS=worker1.host,worker2.host
      - ZK_ID=1
      - HIVE_DB_PASSWORD=12345
    volumes:
      - ~/openblow/postgres_data:/var/lib/postgresql/16/main
      - ~/openblow/wms:/home/hadoop/wms
    ports:
      - "9870:9870"   # HDFS UI
      - "8088:8088"   # YARN UI
      - "9092:9092"   # 
      - "2181:2181"   # 
      - "18080:18080" # Spark History Server
      - "16010:16010" # HBase

  worker1:
    image: mitrakov/openblow:1.0.0
    hostname: worker1.host
    environment:
      - IS_MASTER=false
      - MASTER_HOST=openblow.host
      - WORKER_HOSTS=worker1.host,worker2.host
      - ZK_ID=2

  worker2:
    image: mitrakov/openblow:1.0.0
    hostname: worker2.host
    environment:
      - IS_MASTER=false
      - MASTER_HOST=openblow.host
      - WORKER_HOSTS=worker1.host,worker2.host
      - ZK_ID=3
