name: mariposa
description: "Mariposa Charts"

version: 1.0.1+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  http: 1.6.0                          # http
  syncfusion_flutter_charts: 34.1.33   # charts and diagrams
  shared_preferences: 2.5.4            # local key-value storage for settings

flutter:
  uses-material-design: true
