CREATE SCHEMA IF NOT EXISTS hh;
CREATE TABLE IF NOT EXISTS hh.import_data (
  vacancy_id                BIGINT        COMMENT 'ID вакансии',
  published                 TIMESTAMP     COMMENT 'Дата публикации',
  name                      STRING        COMMENT 'Заголовок вакансии',
  area_name                 STRING        COMMENT 'Название территории',
  salary_from               INT           COMMENT 'Заработная плата, от',
  salary_to                 INT           COMMENT 'Заработная плата, до',
  currency                  STRING        COMMENT 'Валюта зарплаты',
  salary_frequency          STRING        COMMENT 'Частота выплат, напр. TWICE_PER_MONTH',
  gross                     BOOLEAN       COMMENT 'Gross/Net',
  schedule                  STRING        COMMENT 'Тип графика, напр. fullDay',
  employment                STRING        COMMENT 'Тип трудоустройства, напр. FULL',
  working_hours             ARRAY<STRING> COMMENT 'Раб. часы, напр. HOURS_8',
  schedule_by_days          ARRAY<STRING> COMMENT 'График работы, напр. FIVE_ON_TWO_OFF',
  company_name              STRING        COMMENT 'Название компании',
  work_formats              ARRAY<STRING> COMMENT 'Форматы работы, напр. ON_SITE',
  metro                     STRING        COMMENT 'Ближ. станция метрополитена',
  district                  STRING        COMMENT 'Район/микрорайон',
  address                   STRING        COMMENT 'Адрес полный',
  created                   TIMESTAMP     COMMENT 'Дата создания',
  experience                STRING        COMMENT 'Опыт работы, напр. between1And3',
  user_test                 BOOLEAN       COMMENT 'Тестовое задание',
  internship                BOOLEAN       COMMENT 'Интернатура',
  night_shifts              BOOLEAN       COMMENT 'Ночные смены',
  accept_labor_contract     BOOLEAN       COMMENT 'Принимает ли по труд. контракту',
  experimental              ARRAY<STRING> COMMENT 'Пересмотр после исп. срока, напр. newCompensationModes',
  responses                 INT           COMMENT 'Откликов',
  responses_total           INT           COMMENT 'Откликов всего',
  company_id                BIGINT        COMMENT 'ID компании',
  company_category          STRING        COMMENT 'Категория юр. лица, напр. COMPANY',
  company_url               STRING        COMMENT 'Web-адрес компании',
  company_acc               BOOLEAN       COMMENT 'Аккредитация компании',
  company_reviews           STRING        COMMENT 'Просмотров',
  company_reviews_cnt       INT           COMMENT 'Просмотров (всего)',
  salary_per_mode_from      INT           COMMENT 'Заработная плата за ед. Mode, от',
  salary_per_mode_to        INT           COMMENT 'Заработная плата за ед. Mode, до',
  salary_mode               STRING        COMMENT 'Тип вр. отрезка выплат, напр. MONTH',
  area_id                   INT           COMMENT 'ID территории',
  snippet_req               STRING        COMMENT 'Фрагмент текста требований к вакансии',
  snippet_resp              STRING        COMMENT 'Фрагмент текста рабочих задач',
  snippet_cond              STRING        COMMENT 'Фрагмент текста условий трудоустройства',
  snippet_skill             STRING        COMMENT 'Фрагмент текста требуемых навыков',
  api_vacancy_id   BIGINT    NOT NULL     COMMENT 'Internal: ID обр. вакансии в URL API запроса',
  api_capture_date TIMESTAMP NOT NULL     COMMENT 'Internal: время API запроса'
)
COMMENT 'Базовая таблица с сырыми данными для hh.ru'
STORED AS PARQUET;
