# docker build --tag mitrakov/hadoop-krb:1.0.0 .
FROM mitrakov/hadoop:1.0.0
LABEL author="Artem Mitrakov (mitrakov-artem@yandex.ru)"


# add HashiCorp repository (VPN needed!!!!!!!!!!!!!!!!!)
RUN wget --output-document=- https://apt.releases.hashicorp.com/gpg | gpg --dearmor --output /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list && \
    apt update

# krb5     kerberos
# libsasl2 extra SASL modules for GSSAPI
# netcat   nc
# vault    hashicorp vault
# jq       jq
RUN apt install --yes krb5-kdc krb5-admin-server libsasl2-modules-gssapi-mit netcat-openbsd vault jq

# extra ENV variables for Kerberos/Vault
ENV VAULT_HOME=/var/lib/vault
ENV KEYTABS_DIR=/etc/security/keytabs
ENV CERTS_DIR=/etc/vault/certs
ENV KAFKA_OPTS="-Djava.security.auth.login.config=$KAFKA_HOME/config/kafka_jaas.conf"

# add extra user
RUN useradd --create-home --shell /bin/bash tommy


USER hadoop

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
