# docker build --tag mitrakov/hadoop:1.0.0 .
FROM mitrakov/hadoop-tools:1.0.0
LABEL author="Artem Mitrakov (mitrakov-artem@yandex.ru)"

# extra env variables, keep it after massive downloads
# the HADOOP_CONF_DIR is needed for Yarn
ENV HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop

# must-have
RUN echo "export JAVA_HOME=$JAVA_HOME" >> $HADOOP_CONF_DIR/hadoop-env.sh
RUN echo "export JAVA_HOME=$JAVA_HOME" >> $HBASE_HOME/conf/hbase-env.sh

# ...
ENV AIRFLOW_HOME=/opt/airflow
ENV PATH=$PATH:/home/hadoop/.local/bin

# add hadoop user; add to sudoers; create folder for hadoop data; chown folders to hadoop:hadoop
RUN useradd --create-home --shell /bin/bash hadoop && \
    echo "hadoop ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    mkdir $HADOOP_HOME/dfs && \
    mkdir $HADOOP_HOME/logs && \
    mkdir $ZOOKEEPER_HOME/data && \
    mkdir $KAFKA_HOME/data && \
    mkdir $AIRFLOW_HOME && \
    chown -R hadoop:hadoop $HADOOP_HOME && \
    chown -R hadoop:hadoop $HIVE_HOME && \
    chown -R hadoop:hadoop $HBASE_HOME && \
    chown -R hadoop:hadoop $ZOOKEEPER_HOME && \
    chown -R hadoop:hadoop $KAFKA_HOME && \
    chown -R hadoop:hadoop $AIRFLOW_HOME
USER hadoop

# install Apache Airflow
RUN pip install "apache-airflow[celery]==3.0.6" --no-cache-dir --break-system-packages --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-3.0.6/constraints-3.12.txt"
RUN pip install --no-cache-dir --break-system-packages psycopg2-binary asyncpg
RUN pip install --no-cache-dir --break-system-packages apache-airflow-providers-apache-spark

# SSH passwordless login for Hadoop
RUN ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa && \
    cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

# TODO: psycopg2 probably not needed, also check asyncpg
# TODO, move up
RUN mkdir -p $AIRFLOW_HOME/dags

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
