# docker build --tag mitrakov/openphlow:1.0.0 .
FROM mitrakov/openphlow-base:1.0.0
LABEL author="Artem Mitrakov (mitrakov-artem@yandex.ru)"

USER hadoop

RUN wget --directory-prefix $SPARK_HOME/jars/ https://repo1.maven.org/maven2/org/apache/hbase/connectors/spark/hbase-spark/1.0.1/hbase-spark-1.0.1.jar
RUN wget --directory-prefix $SPARK_HOME/jars/ https://repo1.maven.org/maven2/org/apache/hbase/connectors/spark/hbase-spark-protocol/1.0.1/hbase-spark-protocol-1.0.1.jar

COPY openphlow.sh /openphlow.sh
ENTRYPOINT ["/bin/bash", "/openphlow.sh"]
