CREATE TABLE IF NOT EXISTS planet.t_import (
    profile_url                         STRING          COMMENT 'PRIMARY KEY: Полный URL-адрес профиля пользователя',
    name_age                            STRING          COMMENT 'Имя и возраст пользователя (например: Алла, 27)',
    city                                STRING          COMMENT 'Город проживания',
    photo_url                           STRING          COMMENT 'Прямая ссылка на главную фотографию профиля',
    visitors                            INT             COMMENT 'Текущее количество онлайн-посетителей на анкете',
    personal_appearance                 STRING          COMMENT 'Внешние данные (рост, вес, телосложение, цвет глаз)',
    personal_status                     STRING          COMMENT 'Семейное положение / статус отношений',
    personal_children                   STRING          COMMENT 'Наличие детей',
    personal_pets                       STRING          COMMENT 'Наличие домашних животных',
    personal_housing                    STRING          COMMENT 'Жилищные условия пользователя',
    personal_has_car                    STRING          COMMENT 'Наличие личного автомобиля',
    personal_education                  STRING          COMMENT 'Общее образование',
    personal_university                 STRING          COMMENT 'Учебное заведение',
    personal_graduate_year              STRING          COMMENT 'Год выпуска',
    personal_income                     STRING          COMMENT 'Уровень дохода пользователя',
    personal_industry                   STRING          COMMENT 'Сфера профессиональной деятельности',
    personal_job                        STRING          COMMENT 'Конкретная должность пользователя',
    personal_smoking                    STRING          COMMENT 'Отношение к курению',
    personal_alcohol                    STRING          COMMENT 'Отношение к алкоголю',
    personal_languages                  ARRAY<STRING>   COMMENT 'Массив языков, которыми владеет пользователь',
    personal_sports                     ARRAY<STRING>   COMMENT 'Массив видов спорта, которыми занимается пользователь',
    quote                               STRING          COMMENT 'Текстовый статус / цитата пользователя',
    seeking                             STRING          COMMENT 'Текст из блока требований к поиску (Я ищу...)',
    about                               STRING          COMMENT 'Текст из свободного описания (Свободно о себе)',
    target_search                       STRING          COMMENT 'Текст из блока целей (Кого я хочу найти)',
    interests                           ARRAY<STRING>   COMMENT 'Массив тегов интересов пользователя',
    portrait_your_education             STRING          COMMENT 'Детальное описание образования из анкеты',
    portrait_favorite_music             STRING          COMMENT 'Любимые музыкальные жанры и исполнители',
    portrait_favorite_movies            STRING          COMMENT 'Любимые фильмы, сериалы и шоу',
    portrait_favorite_books             STRING          COMMENT 'Любимые книги и авторы',
    portrait_favorite_dishes            STRING          COMMENT 'Любимые блюда и предпочтения в еде',
    portrait_favorite_cities            STRING          COMMENT 'Любимые города и страны для путешествий или жизни',
    portrait_favorite_hobby             STRING          COMMENT 'Любимые занятия',
    portrait_favorite_places            STRING          COMMENT 'Любимые места (парки, заведения, локации)',
    portrait_best_thing                 STRING          COMMENT 'Мнение пользователя о самом хорошем в жизни',
    portrait_worst_thing                STRING          COMMENT 'Мнение пользователя о самом ужасном в жизни',
    portrait_valued_qualities           STRING          COMMENT 'Качества, которые пользователь ценит в людях',
    portrait_what_forgive               STRING          COMMENT 'Что пользователь мог бы простить, а что категорически нет',
    portrait_religion                   STRING          COMMENT 'Какое место занимает религия в жизни пользователя',
    portrait_strengths                  STRING          COMMENT 'Заявленные достоинства характера',
    portrait_weaknesses                 STRING          COMMENT 'Заявленные недостатки характера',
    portrait_job_interesting            STRING          COMMENT 'Чем пользователю интересна его работа',
    portrait_adventure                  STRING          COMMENT 'Самый авантюрный поступок в жизни',
    portrait_tv                         STRING          COMMENT 'Мнение о телевидении и телепередачах',
    portrait_profanity                  STRING          COMMENT 'Отношение пользователя к использованию мата',
    api_capture_date             TIMESTAMP NOT NULL     COMMENT 'Internal: время API запроса'
)
COMMENT 'Базовая таблица с сырыми данными для loveplanet.ru'
STORED AS PARQUET;
